[package]
name = "ausgleichende_gerechtigkeit"
authors = ["Leon Fuss<leon.fuss@icloud.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
diesel = {version =  "1.4.8", features = ["sqlite", "extras"]}
dotenv = "0.15.0"
r2d2 = "0.8.9"
rocket = {version =  "0.5.0-rc.1", features = ["secrets"]}
rocket_sync_db_pools = { version = "0.1.0-rc.1", features = ["diesel_sqlite_pool"], default-features = false }
serde = "1.0.136"
serde_json = "1.0.79"
