newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"

# unstable featues below requires nighly rustfmt
unstable_features = true
version = "Two"

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
